### PR TITLE
add Xref and Dref

### PR DESCRIPTION
**Pull request by dukup11ch1**
I do this

### CODE REVIEW

**Comment by williballenthin** [comment]
awesome!

would you please add a couple unit tests that demonstrate that these routines match the results provided by IDAPython? use IDA interactively to get the xref counts, and then assert that they match what this routines yield.

**Comment by williballenthin** [comment]
CI failure is a memory issue limitation on travis. not a problem here.

**Comment by dukup11ch1** [comment]
sorry for my mistake

**Comment by dukup11ch1** [comment]
return value is not match with idapython

**Pull request closed without merging**
