### PR TITLE
revise xref return and add Xref

### PR DESCRIPTION
**Pull request by dukup11ch1**

### CODE REVIEW

**Comment by dukup11ch1** [comment]
image

maybe this is match...

**Comment by dukup11ch1** [comment]
i change .src to .frm, and .dst to .to
the testcase use .src or .dst.
idapython use .frm, .to instead of .src,.dst

**Comment by dukup11ch1** [comment]
i change .src to .frm, and .dst to .to
the testcase use .src or .dst.
idapython use .frm, .to instead of .src,.dst

**Comment by williballenthin** [comment]
thanks @dukup11ch1 for providing an initial implementation of `XrefsFrom` and `XrefsTo`! i've merged those commits along with some further changes that fix some typos and ensure that all tests continue to pass. thanks also for pointing out the differences in the `Xref` type.

please check out the further changes i made to the PR here: https://github.com/williballenthin/python-idb/compare/dbc0661712477a11e326f50b7612ee8f4f14b35c...6f7c5c17ae6dbb936a7deddc2abe25c5eb8e82f7

this code is now in master. i'll tag a new release pretty soon.

**Comment by dukup11ch1** [comment]
Thx!

**Pull request merged**
